# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Trabajos\9cuatrimestre\mineria_de_datos\corte3\perceptron_mineria\Views\home_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 231)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.899, fx:0.5, fy:0.5, stop:0.0597015 rgba(50, 50, 50, 255), stop:1 rgba(83, 83, 83, 255));\n"
"}\n"
"\n"
"QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -50, 1191, 651))
        self.widget.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(56, 56, 56);\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(450, 70, 61, 21))
        self.label.setStyleSheet("font: 87 10pt \"Segoe UI Black\";\n"
"")
        self.label.setObjectName("label")
        self.spinBox_w0_0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinBox_w0_0.setGeometry(QtCore.QRect(230, 110, 81, 31))
        self.spinBox_w0_0.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:2px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.spinBox_w0_0.setDecimals(4)
        self.spinBox_w0_0.setMaximum(100.0)
        self.spinBox_w0_0.setSingleStep(1.0)
        self.spinBox_w0_0.setObjectName("spinBox_w0_0")
        self.spinBox_w0_1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinBox_w0_1.setGeometry(QtCore.QRect(360, 110, 81, 31))
        self.spinBox_w0_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:2px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.spinBox_w0_1.setDecimals(4)
        self.spinBox_w0_1.setMaximum(100.0)
        self.spinBox_w0_1.setSingleStep(1.0)
        self.spinBox_w0_1.setObjectName("spinBox_w0_1")
        self.spinBox_w0_2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinBox_w0_2.setGeometry(QtCore.QRect(490, 110, 81, 31))
        self.spinBox_w0_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:2px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.spinBox_w0_2.setDecimals(4)
        self.spinBox_w0_2.setMaximum(100.0)
        self.spinBox_w0_2.setSingleStep(1.0)
        self.spinBox_w0_2.setObjectName("spinBox_w0_2")
        self.label_entrenamiento_red_neuronal = QtWidgets.QLabel(self.widget)
        self.label_entrenamiento_red_neuronal.setGeometry(QtCore.QRect(290, 20, 381, 21))
        self.label_entrenamiento_red_neuronal.setStyleSheet("font: 87 12pt \"Segoe UI Black\";")
        self.label_entrenamiento_red_neuronal.setObjectName("label_entrenamiento_red_neuronal")
        self.spinBox_w0_3 = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinBox_w0_3.setGeometry(QtCore.QRect(620, 110, 81, 31))
        self.spinBox_w0_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:2px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.spinBox_w0_3.setDecimals(4)
        self.spinBox_w0_3.setMaximum(100.0)
        self.spinBox_w0_3.setSingleStep(1.0)
        self.spinBox_w0_3.setObjectName("spinBox_w0_3")
        self.label_flowerType = QtWidgets.QLabel(self.widget)
        self.label_flowerType.setGeometry(QtCore.QRect(410, 170, 131, 21))
        self.label_flowerType.setText("")
        self.label_flowerType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flowerType.setObjectName("label_flowerType")
        self.pushButton_ejecutar = QtWidgets.QPushButton(self.widget)
        self.pushButton_ejecutar.setGeometry(QtCore.QRect(420, 210, 121, 41))
        self.pushButton_ejecutar.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(30, 30, 30);\n"
"color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";")
        self.pushButton_ejecutar.setObjectName("pushButton_ejecutar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PESOS"))
        self.label_entrenamiento_red_neuronal.setText(_translate("MainWindow", "ENTRENAMIENTO DE RED NEURONAL"))
        self.pushButton_ejecutar.setText(_translate("MainWindow", "EJECUTAR"))
